/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "gpio.h"
#include "timer.h"
#include "pwm.h"
#include <stdint.h>
#include<stm32f4xx.h>

void delay_with_button(uint32_t *delay, uint32_t *press_count)
{
    *delay = (*delay == 400) ? 300 : (*delay == 300) ? 200 : (*delay == 200) ? 150 :400;
    *press_count = (*press_count >= 4) ? 0 : *press_count + 1;
}

void pwm_intensity(uint32_t *duty_cycle, uint32_t *press_count)
{
    *duty_cycle = (*duty_cycle == 25) ? 50 : (*duty_cycle == 50) ? 75 : (*duty_cycle == 75) ? 100:25;
    *press_count = (*press_count >= 4) ? 0 : *press_count + 1;
}

int main(void)
{
    uint32_t delay = 400;
    uint32_t duty_cycle = 25;
    uint32_t press_count = 0;

    gpio_init();
    Timer_init();
    PWM_init();
    PWM_set_duty_cycle(duty_cycle);

    while(1)
    {
        if (read_button_state())
        {
            delay_with_button(&delay, &press_count);
            pwm_intensity(&duty_cycle, &press_count);
            PWM_set_duty_cycle(duty_cycle);
            Tim2_DELAY(200);  // Debounce delay
            while (read_button_state());  // Wait until button is released
        }

        GPIOA->ODR |= (1 << 5);  // Turn on internal LED (PA5)
        Tim2_DELAY(delay);
        GPIOA->ODR &= ~(1 << 5); // Turn off internal LED (PA5)
        Tim2_DELAY(delay);
    }
}

